---
abstract: "Use lib/ if we're in a dev root"
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  File::Find: 0
  File::Temp: 0
  File::chdir: 0
  List::AllUtils: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: lib-if-dev
no_index:
  directory:
    - corpus
    - t
provides:
  lib::if::dev:
    file: lib/lib/if/dev.pm
    version: 0.001
requires:
  perl: 5.006
resources:
  bugtracker: https://github.com/RsrchBoy/lib-if-dev/issues
  repository: git://github.com/RsrchBoy/lib-if-dev.git
version: 0.001
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/Dist::Zilla::Plugin::NextRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Dist::Zilla::Plugin::Git::NextVersion'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Filter/@Git::CheckFor/Git::CheckFor::CorrectBranch'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::Fixups
      name: '@Filter/@Git::CheckFor/Git::CheckFor::Fixups'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/Dist::Zilla::Plugin::GatherDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/Dist::Zilla::Plugin::PruneCruft'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/Dist::Zilla::Plugin::ExecDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/Dist::Zilla::Plugin::ShareDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/Dist::Zilla::Plugin::MakeMaker'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Filter/Dist::Zilla::Plugin::InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Dist::Zilla::Plugin::Manifest'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::SurgicalPkgVersion
      name: '@Filter/Dist::Zilla::Plugin::SurgicalPkgVersion'
      version: 0.0019
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Filter/Dist::Zilla::Plugin::ReadmeFromPod'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Filter/Dist::Zilla::Plugin::MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/Dist::Zilla::Plugin::ReportVersions::Tiny'
      version: 1.05
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/Dist::Zilla::Plugin::AutoPrereqs'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Dist::Zilla::Plugin::Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@Filter/Dist::Zilla::Plugin::Test::PodSpelling'
      version: 2.002005
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@Filter/Dist::Zilla::Plugin::ConsistentVersionTest'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/Dist::Zilla::Plugin::PodCoverageTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/Dist::Zilla::Plugin::PodSyntaxTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Filter/Dist::Zilla::Plugin::NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Filter/Dist::Zilla::Plugin::EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Filter/Dist::Zilla::Plugin::HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Filter/Dist::Zilla::Plugin::Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/Dist::Zilla::Plugin::ExtraTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::NoSmartCommentsTests
      name: '@Filter/Dist::Zilla::Plugin::NoSmartCommentsTests'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/Dist::Zilla::Plugin::MetaConfig'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/Dist::Zilla::Plugin::MetaJSON'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/Dist::Zilla::Plugin::MetaYAML'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Filter/Dist::Zilla::Plugin::MetaNoIndex'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/Dist::Zilla::Plugin::MetaProvides::Package'
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@Filter/Dist::Zilla::Plugin::GitHub::Meta'
      version: 0.27
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/Dist::Zilla::Plugin::TestRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@Filter/Dist::Zilla::Plugin::CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/Dist::Zilla::Plugin::CheckPrereqsIndexed'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/Dist::Zilla::Plugin::ConfirmRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Filter/Dist::Zilla::Plugin::GitHub::Update'
      version: 0.27
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/Dist::Zilla::Plugin::UploadToCPAN'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Signature
      name: '@Filter/Dist::Zilla::Plugin::Signature'
      version: 1.100930
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Filter/Dist::Zilla::Plugin::Twitter'
      version: 0.017
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Filter/Dist::Zilla::Plugin::InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@Filter/Dist::Zilla::Plugin::ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/Dist::Zilla::Plugin::License'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Filter/Dist::Zilla::Plugin::CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmePodInRoot'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/Dist::Zilla::Plugin::PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300021
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300021
